name: MQTTEx
on: [push, pull_request]

permissions:
  deployments: write
  contents: write
  pull-requests: write

jobs:
  test:
    env:
      GOPATH: /home/runner/work/nats-server
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/github.com/nats-io/nats-server

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set up testing tools and environment
        shell: bash --noprofile --norc -eo pipefail {0}
        id: setup
        run: |
          wget https://github.com/hivemq/mqtt-cli/releases/download/v4.20.0/mqtt-cli-4.20.0.deb
          sudo apt install ./mqtt-cli-4.20.0.deb
          # <>/<> FIXME: use @latest
          go install github.com/ConnectEverything/mqtt-test@7a66171
          go install golang.org/x/perf/cmd/benchstat@latest

      - name: Download benchmark result for ${{ github.base_ref || github.ref_name }}
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          path: src/github.com/nats-io/nats-server/bench
          name: bench-output-${{ runner.os }}
          branch: ${{ github.base_ref || github.ref }}

      - name: Run tests and benchmarks
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          cd src/github.com/nats-io/nats-server
          # ls -lsa bench # <>/<>
          go test -v --run='MQTTEx' ./server
          go test --timeout=20m --run='-' --bench 'MQTTEx/Server-no-/SUBRET' --benchtime=100x --count=10 ./server | tee output.txt

      - name: Compare benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: go
          output-file-path: src/github.com/nats-io/nats-server/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          comment-always: true
          alert-threshold: 110%
          comment-on-alert: true
          fail-on-alert: true
          external-data-json-path: src/github.com/nats-io/nats-server/bench/benchmark-data.json

      - name: Store benchmark result for ${{ github.ref_name }}
        uses: actions/upload-artifact@v3
        with:
          path: src/github.com/nats-io/nats-server/bench
          name: bench-output-${{ runner.os }}

