name: NATS Server Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-cluster-1:
    name: Lev MQTT test
    runs-on: ${{ vars.GHA_WORKER_LARGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run unit tests
        run: go test -race -v -run=TestMQTTSubRetained ./server/... -count=100 -timeout=30m -failfast
